// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package knloop

import (
	"fmt"
	"strings"
	"unicode"

	"google.golang.org/adk/agent"
	"google.golang.org/adk/agent/llmagent"
	"google.golang.org/adk/session"
)

// Task is a single discovery question with its collected evidence.
type Task struct {
	Question string `json:"question"`
	Evidence string `json:"evidence,omitempty"`
}

// Plan is the full set of discovery tasks generated by the planner.
type Plan struct {
	Tasks []Task `json:"tasks"`
}

// generatePlan runs the planning ralph loop (Step 2).
//
// It calls the planner LLM up to cfg.MaxPlanIterations times. After each
// attempt it deterministically validates the plan. On failure it injects
// specific failure messages via stateSet so the planner can self-correct.
//
// Returns (plan, true) on success or max-iterations-exceeded.
// Returns (Plan{}, false) if the consumer stopped early.
func generatePlan(ctx agent.InvocationContext, base llmagent.BaseAgentConfig, cfg *Config, yield func(*session.Event, error) bool) (Plan, bool) {
	for i := 0; i < cfg.MaxPlanIterations; i++ {
		ag, err := llmagent.New(llmagent.Config{
			Name:                     "knloop_planner",
			Model:                    base.Model,
			Tools:                    base.Tools,
			Toolsets:                 base.Toolsets,
			Instruction:              plannerPrompt,
			IncludeContents:          llmagent.IncludeContentsNone,
			DisallowTransferToParent: true,
			DisallowTransferToPeers:  true,
		})
		if err != nil {
			yield(nil, fmt.Errorf("knloop: create planner agent: %w", err))
			return Plan{}, false
		}

		text, ok := drainCapture(ag, ctx, yield)
		if !ok {
			return Plan{}, false
		}

		plan := parsePlan(text)

		// Deterministic validation — no LLM involved.
		skillCtx := stateGetString(ctx, stateSkillContext)
		if failures := validatePlan(plan, skillCtx, cfg.MinPlanTasks); len(failures) > 0 {
			stateSet(ctx, statePlanFailures, strings.Join(failures, "\n"))
			continue
		}

		// Plan passed all checks.
		stateSet(ctx, statePlanFailures, "")
		return plan, true
	}

	// Max iterations reached — return an empty plan and let synthesis note no evidence.
	stateSet(ctx, statePlanFailures, "")
	return Plan{}, true
}

// parsePlan converts the planner's plain-text bullet list into a Plan.
// It accepts lines prefixed with "- ", "* ", "• ", or a number+dot ("1. ").
// Blank lines and lines with no recognisable question content are skipped.
func parsePlan(text string) Plan {
	var tasks []Task
	for _, line := range strings.Split(text, "\n") {
		q := strings.TrimSpace(line)
		// Strip common bullet/list prefixes.
		q = strings.TrimPrefix(q, "- ")
		q = strings.TrimPrefix(q, "* ")
		q = strings.TrimPrefix(q, "• ")
		// Strip leading "N. " numbered-list prefix.
		if idx := strings.Index(q, ". "); idx > 0 && idx <= 3 {
			if allDigits(q[:idx]) {
				q = q[idx+2:]
			}
		}
		q = strings.TrimSpace(q)
		if q != "" {
			tasks = append(tasks, Task{Question: q})
		}
	}
	return Plan{Tasks: tasks}
}

// allDigits reports whether s consists entirely of ASCII digit characters.
func allDigits(s string) bool {
	for _, r := range s {
		if !unicode.IsDigit(r) {
			return false
		}
	}
	return len(s) > 0
}

// validatePlan runs deterministic checks on the plan.
// It returns a list of failure descriptions; an empty list means the plan is valid.
func validatePlan(plan Plan, skillContext string, minTasks int) []string {
	var failures []string

	if len(plan.Tasks) < minTasks {
		failures = append(failures, fmt.Sprintf(
			"plan has only %d tasks but at least %d are required; add more specific discovery questions",
			len(plan.Tasks), minTasks,
		))
	}

	seen := make(map[string]bool, len(plan.Tasks))
	for i, t := range plan.Tasks {
		q := strings.TrimSpace(t.Question)
		if q == "" {
			failures = append(failures, fmt.Sprintf("task %d has an empty question; every task must have a non-empty question", i+1))
			continue
		}
		lower := strings.ToLower(q)
		for _, conj := range []string{" and ", " or ", " but ", " also "} {
			if strings.Contains(lower, conj) {
				failures = append(failures, fmt.Sprintf(
					"task %d is compound (contains %q): %q — split it into separate tasks",
					i+1, strings.TrimSpace(conj), q,
				))
				break
			}
		}
		if seen[lower] {
			failures = append(failures, fmt.Sprintf("task %d is a duplicate of an earlier question: %q", i+1, q))
		}
		seen[lower] = true
	}

	// Soft check: at least some questions should reference terms visible in the
	// skill context. This guards against hallucinated or off-topic plans.
	if skillContext != "" && len(plan.Tasks) > 0 {
		lowerCtx := strings.ToLower(skillContext)
		anyMatch := false
		for _, t := range plan.Tasks {
			for _, w := range strings.Fields(strings.ToLower(t.Question)) {
				if len(w) > 3 && strings.Contains(lowerCtx, w) {
					anyMatch = true
					break
				}
			}
			if anyMatch {
				break
			}
		}
		if !anyMatch {
			failures = append(failures, "none of the questions reference terms from the skill context; "+
				"ensure questions are grounded in the observable environment described in the context")
		}
	}

	return failures
}
