// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package knloop

import (
	"encoding/json"
	"fmt"
	"strings"

	"google.golang.org/genai"

	"google.golang.org/adk/agent"
	"google.golang.org/adk/agent/llmagent"
	"google.golang.org/adk/session"
)

// Task is a single discovery question with its collected evidence.
type Task struct {
	Question string `json:"question"`
	Evidence string `json:"evidence,omitempty"`
}

// Plan is the full set of discovery tasks generated by the planner.
type Plan struct {
	Tasks []Task `json:"tasks"`
}

// plannerSchema defines the structured output for the planning step.
// The planner has no other tools, so ADK uses native JSON response mode.
var plannerSchema = &genai.Schema{
	Type: genai.TypeObject,
	Properties: map[string]*genai.Schema{
		"tasks": {
			Type:        genai.TypeArray,
			Description: "List of small, focused discovery tasks.",
			Items: &genai.Schema{
				Type: genai.TypeObject,
				Properties: map[string]*genai.Schema{
					"question": {
						Type:        genai.TypeString,
						Description: "A single, focused yes/no or factual question about the environment.",
					},
				},
				Required: []string{"question"},
			},
		},
	},
	Required: []string{"tasks"},
}

// generatePlan runs the planning ralph loop (Step 2).
//
// It calls the planner LLM up to cfg.MaxPlanIterations times. After each
// attempt it deterministically validates the plan. On failure it injects
// specific failure messages via stateSet so the planner can self-correct.
//
// Returns (plan, true) on success or max-iterations-exceeded.
// Returns (Plan{}, false) if the consumer stopped early.
func generatePlan(ctx agent.InvocationContext, base llmagent.BaseAgentConfig, cfg *Config, yield func(*session.Event, error) bool) (Plan, bool) {
	for i := 0; i < cfg.MaxPlanIterations; i++ {
		ag, err := llmagent.New(llmagent.Config{
			Name:        "knloop_planner",
			Model:       base.Model,
			Instruction: plannerPrompt,
			OutputSchema: plannerSchema,
			OutputKey:   statePlan,
			// No tools: planner only reads state and generates a plan.
			IncludeContents:         llmagent.IncludeContentsNone,
			DisallowTransferToParent: true,
			DisallowTransferToPeers: true,
		})
		if err != nil {
			yield(nil, fmt.Errorf("knloop: create planner agent: %w", err))
			return Plan{}, false
		}

		if !drain(ag, ctx, yield) {
			return Plan{}, false
		}

		// Read the plan from session state (saved by OutputKey).
		planJSON := stateGetString(ctx, statePlan)
		plan, parseErr := parsePlan(planJSON)
		if parseErr != nil {
			stateSet(ctx, statePlanFailures, "Could not parse plan JSON: "+parseErr.Error()+". Ensure your response is valid JSON matching the required schema.")
			continue
		}

		// Deterministic validation — no LLM involved.
		skillCtx := stateGetString(ctx, stateSkillContext)
		if failures := validatePlan(plan, skillCtx, cfg.MinPlanTasks); len(failures) > 0 {
			stateSet(ctx, statePlanFailures, strings.Join(failures, "\n"))
			continue
		}

		// Plan passed all checks.
		stateSet(ctx, statePlanFailures, "")
		return plan, true
	}

	// Max iterations reached — use whatever plan was last produced (may be partial).
	stateSet(ctx, statePlanFailures, "")
	planJSON := stateGetString(ctx, statePlan)
	plan, _ := parsePlan(planJSON)
	return plan, true
}

// parsePlan deserialises the JSON string saved by the planner's OutputKey.
func parsePlan(jsonStr string) (Plan, error) {
	if strings.TrimSpace(jsonStr) == "" {
		return Plan{}, fmt.Errorf("plan JSON is empty")
	}
	var plan Plan
	if err := json.Unmarshal([]byte(jsonStr), &plan); err != nil {
		return Plan{}, fmt.Errorf("unmarshal: %w", err)
	}
	return plan, nil
}

// validatePlan runs deterministic checks on the plan.
// It returns a list of failure descriptions; an empty list means the plan is valid.
func validatePlan(plan Plan, skillContext string, minTasks int) []string {
	var failures []string

	if len(plan.Tasks) < minTasks {
		failures = append(failures, fmt.Sprintf(
			"plan has only %d tasks but at least %d are required; add more specific discovery questions",
			len(plan.Tasks), minTasks,
		))
	}

	seen := make(map[string]bool, len(plan.Tasks))
	for i, t := range plan.Tasks {
		q := strings.TrimSpace(t.Question)
		if q == "" {
			failures = append(failures, fmt.Sprintf("task %d has an empty question; every task must have a non-empty question", i+1))
			continue
		}
		lower := strings.ToLower(q)
		if strings.Contains(lower, " and ") {
			failures = append(failures, fmt.Sprintf(
				"task %d is compound (contains 'and'): %q — split it into two separate tasks",
				i+1, q,
			))
		}
		if seen[lower] {
			failures = append(failures, fmt.Sprintf("task %d is a duplicate of an earlier question: %q", i+1, q))
		}
		seen[lower] = true
	}

	// Soft check: at least some questions should reference terms visible in the
	// skill context. This guards against hallucinated or off-topic plans.
	if skillContext != "" && len(plan.Tasks) > 0 {
		lowerCtx := strings.ToLower(skillContext)
		anyMatch := false
		for _, t := range plan.Tasks {
			for _, w := range strings.Fields(strings.ToLower(t.Question)) {
				if len(w) > 3 && strings.Contains(lowerCtx, w) {
					anyMatch = true
					break
				}
			}
			if anyMatch {
				break
			}
		}
		if !anyMatch {
			failures = append(failures, "none of the questions reference terms from the skill context; "+
				"ensure questions are grounded in the observable environment described in the context")
		}
	}

	return failures
}
